name: Check
on:
  push:
    branches:
      - "**"
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: "15.14"
          cache: "npm"
          cache-dependency-path: package-lock.json
      - name: Run lint script
        run: npm run lint

  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: "15.14"
          cache: "npm"
          cache-dependency-path: package-lock.json
      - name: Run build script
        run: npm run build

  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: "15.14"
          cache: "npm"
          cache-dependency-path: package-lock.json
      - name: Run tests
        run: npm test
